
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: moviesdb
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"

  backend:
    build: ./server
    working_dir: /app
    volumes:
      - ./server:/app
    environment:
      DATABASE_URL: "mysql://root:example@db:3306/moviesdb"
      JWT_SECRET: "supersecretjwt"
      S3_ENDPOINT: "http://minio:9000"
      S3_ACCESS_KEY: "minio"
      S3_SECRET_KEY: "minio123"
      S3_BUCKET: "posters"
      PORT: 4000
    depends_on:
      - db
      - minio
    ports:
      - "4000:4000"

volumes:
  db-data:
